FROM node:14-alpine AS build

WORKDIR /app

COPY package.json ./

RUN npm install

RUN npm run build --prod	

FROM nginx:1.17.1-alpine AS prod-stage
COPY --from=build /app/dist/Front /usr/share/ngnix/html
EXPOSE 4200
CMD ["nginx","-g","daemon off;"]